FROM ubuntu:14.04.5

MAINTAINER Deogracias Maroto

# Install Nginx
RUN apt-get update
RUN apt-get -y -q install nginx

# Copy Front files
COPY web/ /opt/front/web
COPY index.html /opt/front
COPY ./entrypoint.sh entrypoint.sh
RUN chmod +x /entrypoint.sh

# Add nginx configuration files
ADD global.conf /etc/nginx/conf.d/
ADD nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["/entrypoint.sh"]
