version: "2.1"

services:

  back:
    build:
      context: .
      dockerfile: Dockerfile
    image: back:latest
    ports:
      - "3080:8000"

  front:
    build:
      context: .
      dockerfile: Dockerfile_front
    image: front:latest
    restart: always
    ports:
      - "1080:80"
